//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploye
    {
        public int EmployeID { get; set; }
        public string UserName { get; set; }
        public string Surname { get; set; }
        public string IdNumber { get; set; }
        public string JMBG { get; set; }
        public string DateOfBirth { get; set; }
        public int GenderID { get; set; }
        public string Number { get; set; }
        public int SectorID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> Menager_ID { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        public virtual tblLOCATION tblLOCATION { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
